// <auto-generated />
using AvionesDistribuidos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvionesDistribuidos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250406063153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvionesDistribuidos.Models.Ciudad", b =>
                {
                    b.Property<int>("Id_Ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ciudad"));

                    b.Property<int>("Id_Pais")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Ciudad");

                    b.HasIndex("Id_Pais");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Destino", b =>
                {
                    b.Property<int>("Id_Destino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Destino"));

                    b.Property<string>("Aeropuerto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion_Corta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Ciudad")
                        .HasColumnType("int");

                    b.HasKey("Id_Destino");

                    b.HasIndex("Id_Ciudad");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Pais", b =>
                {
                    b.Property<int>("Id_Pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pais"));

                    b.Property<string>("Codigo_Iso")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Pais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Ciudad", b =>
                {
                    b.HasOne("AvionesDistribuidos.Models.Pais", "Pais")
                        .WithMany("Ciudades")
                        .HasForeignKey("Id_Pais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Destino", b =>
                {
                    b.HasOne("AvionesDistribuidos.Models.Ciudad", "Ciudad")
                        .WithMany("Destinos")
                        .HasForeignKey("Id_Ciudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Ciudad", b =>
                {
                    b.Navigation("Destinos");
                });

            modelBuilder.Entity("AvionesDistribuidos.Models.Pais", b =>
                {
                    b.Navigation("Ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
